# Generated by Django 2.0.13 on 2019-04-15 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
