# Generated by Django 2.0.13 on 2019-04-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_auto_20190331_0632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='TV Mounting', max_length=50)),
                ('upper_range', models.IntegerField(default=15000)),
                ('lower_range', models.IntegerField(default=500)),
                ('owner', models.CharField(default='Peterson', max_length=50)),
                ('location', models.CharField(default='Peterson', max_length=50)),
                ('deadline', models.DateTimeField()),
            ],
        ),
    ]
