# Generated by Django 2.0.13 on 2019-04-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0004_jobs_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job_description',
            field=models.TextField(default="This job should be done as first as posible, can't wait for the bids", max_length=300),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='location',
            field=models.CharField(default='Kisumu', max_length=50),
        ),
    ]
